import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Header from "../components/Header";
import Footer from "../components/Footer";
import Link from "next/link";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className="{inter.className} flex flex-col text-white-200 min-w-screen min-h-screen max-w-3xl mx-auto">
        <Header />
        <Link
          href="about-me"
          className="text-3xl pt-4 text-white-400 border p-3 mb-3 hover:text-blue-700"
        >
          Games n dat
        </Link>
        <Link
          href="other-things"
          className="text-3xl pt-4 text-white-400 border p-3 mb-3 hover:text-blue-700"
        >
          Other tings n dat
        </Link>

        {children}
        <Footer />
      </body>
    </html>
  );
}
