import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Header from "../components/Header";
import Footer from "../components/Footer";
import Link from "next/link";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className="{inter.className} flex flex-col text-cyan-200 min-w-screen min-h-screen max-w-3xl mx-auto">
        <Header />
        <Link href="about-me">Games n dat</Link>
        <Link href="other-things">Other tings n dat</Link>

        {children}
        <Footer />
      </body>
    </html>
  );
}
